### ISSUE TITLE
Specific PowerShell Version Requirement?

### ISSUE THREAD

**Issue by Gelob** [brittandeyoung/PRTGtopagerdutyAPI#1]
Is there a specific powershell version requirement? I'm trying to run this with the following version and get a lot of errors. A PRTG simulated test or test notification doesn't work so I'm trying to run it directly to test.

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018

```

```
PS C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE> .\prtgtopagerduty.ps1 -API_URL 'https://events.pagerdu
ty.com/v2/enqueue' -ROUTING_KEY 'mykeyhere' -Sensor %sensorid% -SiteName '%sitename' -Device '%de
vice - %name' -DeviceId '%deviceid' -Name '%name' -Status '%status' -Down '%down' -DateTime '%datetime' -LinkDevice '%li
nkdevice' -Message '%message'
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:87 char:11
+ status = "$($Status) $($Down) on $($DateTime)";
+           ~~
Unexpected token '$(' in expression or statement.
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:87 char:11
+ status = "$($Status) $($Down) on $($DateTime)";
+           ~
The hash literal was incomplete.
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:87 char:10
+ status = "$($Status) $($Down) on $($DateTime)";
+          ~
The hash literal was incomplete.
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:87 char:22
+ status = "$($Status) $($Down) on $($DateTime)";
+                      ~~
Unexpected token '$(' in expression or statement.
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:87 char:31
+ status = "$($Status) $($Down) on $($DateTime)";
+                               ~~
Unexpected token 'on' in expression or statement.
At C:\Program Files (x86)\PRTG Network Monitor\Notifications\EXE\prtgtopagerduty.ps1:102 char:97
+ ... URL -Method POST -Body $postPagerDuty -ContentType "application/json"
+                                                                         ~
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by brittandeyoung** [comment]
I am running the same version of power shell you are on my PRTG server. Please try the following. Run the script and pass in real parameters. Here is an example, just replace the routing key with yours. You should receive a status code of 202 showing a successful post. 

Create test incident:
.\prtgtopagerduty.ps1 -API_URL 'https://events.pagerduty.com/v2/enqueue' -ROUTING_KEY 'routingkey' -Sensor "testkey" -SiteName 'testname' -Device 'DeviceName' -DeviceId 'DeviceId' -Name 'Name' -Status 'Down' -Down 'Down' -DateTime "1/7/2019 9:12:39 AM" -LinkDevice 'https://www.paessler.com/prtg' -Message 'Simulated error (code: PE034)'

Resolve Test Incident:
.\prtgtopagerduty.ps1 -API_URL 'https://events.pagerduty.com/v2/enqueue' -ROUTING_KEY 'routingkey' -Sensor "testkey" -SiteName 'testname' -Device 'DeviceName' -DeviceId 'DeviceId' -Name 'Name' -Status 'Down ended' -Down 'Down' -DateTime "1/7/2019 9:12:39 AM" -LinkDevice 'https://www.paessler.com/prtg' -Message 'Simulated error (code: PE034)'

These commands will test a few things, first it will make sure your routing key has the correct access, secondly it will provide useful error messages for troubleshooting if it fails. Please let me know how this goes.

**Comment by Gelob** [comment]
@brittandeyoung I was getting the same error. I had copy/pasted the RAW script from one computer to another and I guess that messed up the formatting. I viewed it as RAW on my PRTG server and saved it that way and everything appears to be working. Thank you for this!

**Comment by brittandeyoung** [comment]
Glad to see it is working for you! All the other methods I found out there for this integration were way more complicated than necessary. Glad to see this can help someone else.
